#!/usr/bin/env python3

import datetime
import subprocess
import shlex
import os
import sys

rotateOrder = ['columbia', 'cornell', 'rpi', 'suny', 'cuny', 'nyu']
highPriorityValue = 100
normalPriorityValue = 10
lowPriorityValue = 9

def GetWeekNum():
    today = datetime.datetime.today()
    return today.isocalendar()[1]-1 # Reindex from 0 instead of 1 because Python is dumb and inconsistent about numeric indexes

def GetThisWeeksInstitution():
    return rotateOrder[GetWeekNum() % len(rotateOrder)]

def UpdateSlurmConfig():
    # Example bash command: cmsh -c 'wlm; jobqueue; use priority; set allowgroups columbia; set allowaccounts columbia; commit'
    CMD=["cmsh", "-c", f"wlm; jobqueue; use priority; set allowgroups {GetThisWeeksInstitution()}; set allowaccounts {GetThisWeeksInstitution()}; commit; show;"]
    try:
        result = subprocess.run(CMD, check=True, text=True, capture_output=True)
        print("Subprocess command run was successful.")
    except subprocess.CalledProcessError as e:
        print("Error: ", e.stderr)

def GetOutgoingInstitution():
    # Get the name of the institution that is losing priority this week
    index = GetWeekNum() - 1
    return rotateOrder[index]

if __name__ == "__main__":
    print(f"=== Partition Priority Rotation Script Beginning: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')} ===")
    print(f"The current date is {datetime.datetime.today().strftime('%Y-%m-%d')}")
    print(f"The current week number is {GetWeekNum()}.")
    print(f"The high-priority partition is being changed from {GetOutgoingInstitution()} to {GetThisWeeksInstitution()}.")
    UpdateSlurmConfig()
    print("=== Run Complete ===\n")

#if __name__ == "__main__":
#    print(f"=== Partition Priority Rotation Script Beginning: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')} ===")
#    dryRun = False
#    if len(sys.argv) > 1 and sys.argv[1] == "-d":
#        print("The partition priority rotation script is executing in DRY RUN mode!")
#        print("No changes will be made to priority.")
#        dryRun = True
#    print(f"The current date is {datetime.datetime.today().strftime('%Y-%m-%d')}")
#    print(f"The current week number is {GetWeekNum()}.")
#    print(f"The high-priority partition is being changed from {GetOutgoingInstitution()} to {GetThisWeeksInstitution()}.")


    #Priority changes are done in this order intentionally to minimize potential scheduler trash
    #Promote the new institution to highPriorityValue
#    if SetPartitionPriorityTier(GetThisWeeksInstitution(), highPriorityValue, dryRun) == True:
#        print(f"Priority of partition {GetThisWeeksInstitution()} has been set to {highPriorityValue}.")
#        #Demote the outgoing institution to normalPriorityValue
#        if SetPartitionPriorityTier(GetOutgoingInstitution(), normalPriorityValue, dryRun) == True:
#            print(f"Priority of partition {GetOutgoingInstitution()} has been set to {normalPriorityValue}.")
#        else:
#            print(f"There was some error attempting to change the priority of partition {GetOutgoingInstitution()} to {normalPriorityValue}.")
#    else:
#        print(f"There was some error attempting to change the priority of partition {GetThisWeeksInstitution()} to {highPriorityValue}.")
#        print(f"Cowardly refusing to change the priority of outgoing institution {GetOutgoingInstitution()} as well.")
    
#    print("=== Run Complete ===\n")
