#!/usr/bin/env python3

# This script processes users in Nvidia Base Command's user list to ensure that
# each user has all necessary directories created as well as a presence in the
# Slurm accounting database.
#
# Arguments: None
#
# This makes use of the EmpyreAI module and ultimately the Base Command API
#   to provide user management capabilities to coordinators without requiring
#   elevated privileges on the cluster.
#
# Return Codes: None
#
# Author: Kali McLennan (Flatiron Institute) - kmclennan@flatironinstitute.org


from EmPyreAI.EmpireUser import EmpireUser
from EmPyreAI.EmpireGroup import EmpireGroup
from EmPyreAI.EmpireSlurm import EmpireSlurm
import EmPyreAI.EmpireUtils as EUtils
import os
import getpass
import sys
from prettytable import PrettyTable
import json
import paramiko
import subprocess
import shlex

created_dirs = []

if __name__ == "__main__":
    slurmAPI = EmpireSlurm()

    for institution in ['cuny', 'suny', 'columbia', 'cornell', 'rpi', 'nyu']:
        thisGroup = EmpireGroup(institution)
        for groupMember in thisGroup.members:
            thisUser = EmpireUser(groupMember)
            userAccounts = slurmAPI.GetUserAccounts(thisUser.username)
            print(userAccounts["accounts"])
            if thisGroup.name not in userAccounts["accounts"]:
                print(f"User {thisUser.username} needs to be added to the {thisGroup.name} account in Slurm")

